<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL4izkws\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL4izkws/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL4izkws.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL4izkws\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerL4izkws\App_KernelProdContainer([
    'container.build_hash' => 'L4izkws',
    'container.build_id' => 'b294e85e',
    'container.build_time' => 1701350204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL4izkws');
