<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9rLJoi\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9rLJoi/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerE9rLJoi.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerE9rLJoi\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerE9rLJoi\App_KernelTestDebugContainer([
    'container.build_hash' => 'E9rLJoi',
    'container.build_id' => 'a321d8bb',
    'container.build_time' => 1699918752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9rLJoi');
