<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXtz6Sp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXtz6Sp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSXtz6Sp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSXtz6Sp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSXtz6Sp\App_KernelDevDebugContainer([
    'container.build_hash' => 'SXtz6Sp',
    'container.build_id' => 'e969fd4d',
    'container.build_time' => 1700135703,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXtz6Sp');
