<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJ6E6xg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJ6E6xg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWJ6E6xg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWJ6E6xg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWJ6E6xg\App_KernelDevDebugContainer([
    'container.build_hash' => 'WJ6E6xg',
    'container.build_id' => 'b11575b9',
    'container.build_time' => 1699956689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJ6E6xg');
