<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQb4sk3l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQb4sk3l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQb4sk3l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQb4sk3l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQb4sk3l\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qb4sk3l',
    'container.build_id' => '4acee742',
    'container.build_time' => 1701123816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQb4sk3l');
